[theme]
# Verde salvia suave, tomado de la imagen
primaryColor = "#769a8c"

# Un fondo muy, muy claro, con un toque de verde/gris
#backgroundColor = "#F5F8F7"

# El fondo de los widgets (inputs, uploaders) será blanco puro
secondaryBackgroundColor = "#FFFFFF"

# Texto oscuro estándar
textColor = "#31333F"

# Fuente limpia
font = "sans serif"